config/routes.rb
Rails.application.routes.draw do
  
  resources :facility_management

  resources :health_facilities
  
  root 'health_facilities#index'

end

app/models/health_facility.rb
class HealthFacility < ActiveRecord::Base
 attr_accessible :lat, :longi, :address, :typeOf, :classOf
end

app/controllers/health_facilities_controller.rb
class HealthFacilitiesController < ApplicationController
    
require 'json'
require 'open-uri'
require 'net/http'
require 'rest-client'
require 'mime-types'
require 'netrc'
require 'http-cookie'

  def index
    #@health_equip_hash = get_Health_Equip_Json["resources"]
    @redir = (session[:search] != params[:search]) || (session[:typeOf] != params[:typeOf])
    if params[:search] != nil
      session[:search] = params[:search]
    end
    if params[:typeOf] != nil
      session[:typeOf] = params[:typeOf]
    end
    @all_types = types_to_show
    @checked_types = checked_types_of_facilities
    @health_facilities = get_health_facilities(checked_types_of_facilities)
    @user_address = get_user_address
    @user_coordinates = get_user_coordinates(get_user_address)
    @geocoder_user_address = Geocoder.address(@user_coordinates)
    @hash = create_facilities_markers(order_facilities(get_user_coordinates(get_user_address), @health_facilities))
    @user_markers = create_user_marker(@user_coordinates)
    @winner = order_facilities(@user_coordinates, @health_facilities).first.first
    @winner_coords = [@winner[:lat], @winner[:longi]]
    if @redir then redirect_to health_facilities_path(:search => session[:search], :typeOf => session[:typeOf]) end
  end

  def checked_types_of_facilities
    if params.has_key?(:typeOf)
      if types_to_show.include? params[:typeOf][0]
        return params[:typeOf][0]
      end
    end
    types_to_show
  end
      
  def create_facilities_markers(distances)
    Gmaps4rails.build_markers(distances) do |health_facility, marker|
      marker.lat health_facility[0][:lat]
      marker.lng health_facility[0][:longi]
      marker.picture health_facility[7]
      marker.infowindow "<p><b>#{health_facility[2]}</b></p>
                          <p>Facility type: #{health_facility[0][:type_of]}</p>
                          <p>Distance: #{health_facility[3].round(2).to_s}km</p>
                          <p>Total capacity: #{health_facility[4].to_s}</p>
                          <p>Current users: #{health_facility[5].to_s}</p>
                          <p>Use ratio: #{health_facility[6].round(4).to_s}</p>"
    end
  end
  
  def create_user_marker(user_coordinates)
    [{:lat => user_coordinates[0], :lng => user_coordinates[1], :infowindow => "<p><b>Hidey-ho! I'm the user!</b></p>Address: #{@geocoder_user_address}</p>",
      :picture => {:url => icons_url[:green], :width => 40, :height => 40}}]
  end
  
  def get_user_address
    if params[:search] then params[:search] else default_address end
  end

  def get_user_coordinates(address)
    Geocoder.coordinates(address)
  end
      
    #get the total capacity of a facility
    def get_total_capacity
        response = JSON.parse(RestClient.post "http://107.170.158.70:3002/resources/data/last", '{"sensor_value":{"capabilities":"info_total_capacity"}}'.to_json, :content_type => :json, :application => :json)
        response["resources"]
    end
    #get the facilities available types
    def get_facilities_types
        response = JSON.parse(RestClient.post "http://107.170.158.70:3002/resources/data/last", '{"sensor_value":{"capabilities":"info_facility_type"}}'.to_json, :content_type => :json, :application => :json)
        response["resources"]
    end
    #get the current users of facilities
    def get_current_users
        response = JSON.parse(RestClient.post "http://107.170.158.70:3002/resources/data/last", '{"sensor_value":{"capabilities":"current_users"}}'.to_json, :content_type => :json, :application => :json)
        response["resources"]
    end
      
  #this method gets the json from resource adapter
  def get_Health_Equip_Json
      #json_response = "http://cpro37690.publiccloud.com.br:3004/discovery/resources?capability=info_facility_type"
      #health_equip_list = JSON.parse(JSON.load(open("http://cpro37690.publiccloud.com.br:3004/discovery/resources?capability=info_facility_type")).to_json)
      health_equip_list = JSON.parse(JSON.load(open("http://107.170.158.70:3004/discovery/resources?capability=info_facility_type")).to_json)
  end
      
  #TODO: create url to do a query for facilities using discovery service
  def create_url_query(types_of_facilities)
  end
  
  #TODO: once discovery query is available, modify this function
  #to convert the json obtained from query to the array with format below
  #as this array is being used to create map markers, calculate distances etc.
  #{:lat=> -23.522787, :longi=> -46.490063, :type_of=> "AMA ESPECIALIDADES", :total_capacity=> random_capacity[0], :current_users=> current_users[0]}
  def query_to_array(query)
    query
  end
  
  #TODO: replace hardcoded facilities with a /get query
  def get_health_facilities(types_of_facilities)
    random_capacity = []
    random_mult = []
    current_users = []
    9.times do |i|
      random_capacity.push(Random.rand(50...200))
      random_mult.push(2 * Random.rand)
      current_users.push((random_mult[i] * random_capacity[i]).floor)
    end
    query = [
      {:lat=> -23.522787, :longi=> -46.490063, :type_of=> "AMA ESPECIALIDADES", :total_capacity=> random_capacity[0], :current_users=> current_users[0]},
      {:lat=> -23.673297, :longi=> -46.773393, :type_of=> "AMA ESPECIALIDADES", :total_capacity=> random_capacity[1], :current_users=> current_users[1]},
      {:lat=> -23.531575, :longi=> -46.651898, :type_of=> "AMBULATORIO DE ESPECIALIDADES", :total_capacity=> random_capacity[2], :current_users=> current_users[2]},
      {:lat=> -23.599363, :longi=> -46.539564, :type_of=> "AMA ESPECIALIDADES", :total_capacity=> random_capacity[4], :current_users=> current_users[4]},
      {:lat=> -23.630816, :longi=> -46.766027, :type_of=> "AMA ESPECIALIDADES", :total_capacity=> random_capacity[6], :current_users=> current_users[6]},
      {:lat=> -23.659403, :longi=> -46.743017, :type_of=> "AMA ESPECIALIDADES", :total_capacity=> random_capacity[7], :current_users=> current_users[7]},
      {:lat=> -23.586723, :longi=> -46.491950, :type_of=> "AMA ESPECIALIDADES", :total_capacity=> random_capacity[8], :current_users=> current_users[8]},
      {:lat=> -23.408249, :longi=> -46.757991, :type_of=> "AMBULATORIO DE ESPECIALIDADES", :total_capacity=> 180, :current_users=> 36},
      {:lat=> -23.497448, :longi=> -46.654057, :type_of=> "AMBULATORIO DE ESPECIALIDADES", :total_capacity=> 217, :current_users=> 79},
      {:lat=> -23.570175, :longi=> -46.575142, :type_of=> "AMBULATORIO DE ESPECIALIDADES", :total_capacity=> 383, :current_users=> 78},
      {:lat=> -23.629079, :longi=> -46.604422, :type_of=> "AMBULATORIO DE ESPECIALIDADES", :total_capacity=> 154, :current_users=> 120},
      {:lat=> -23.49283,  :longi=> -46.600559, :type_of=> "AMBULATORIO DE ESPECIALIDADES", :total_capacity=> 98,  :current_users=> 27},
      {:lat=> -23.476568, :longi=> -46.710942, :type_of=> "AMBULATORIO DE ESPECIALIDADES", :total_capacity=> 120, :current_users=> 61},
      {:lat=> -23.628113, :longi=> -46.645846, :type_of=> "AMBULATORIO DE ESPECIALIDADES", :total_capacity=> 340, :current_users=> 228}, 
      {:lat=> -23.523016, :longi=> -46.651378, :type_of=> "AMBULATORIO DE ESPECIALIDADES", :total_capacity=> 383, :current_users=> 352},
      {:lat=> -23.561088, :longi=> -46.654078, :type_of=> "AMBULATORIO DE ESPECIALIDADES", :total_capacity=> 407, :current_users=> 163},
      {:lat=> -23.652993, :longi=> -46.645012, :type_of=> "AMBULATORIO DE ESPECIALIDADES", :total_capacity=> 147, :current_users=> 142},
      {:lat=> -23.695249, :longi=> -46.65946,  :type_of=> "AMBULATORIO DE ESPECIALIDADES", :total_capacity=> 143, :current_users=> 122},
      {:lat=> -23.548579, :longi=> -46.643979, :type_of=> "AMA ESPECIALIDADES", :total_capacity=> 70,  :current_users=> 59},
      {:lat=> -23.524112, :longi=> -46.716684, :type_of=> "AMA ESPECIALIDADES", :total_capacity=> 165, :current_users=> 82}
      ]
    filtered_query = if types_of_facilities != types_to_show
        query.select do |q|
          q[:type_of] == types_of_facilities
        end
      else
        query
      end
    query_to_array(filtered_query)
  end

  def types_to_show
    IO.read('types_of_facilities').split(",")
  end
  
  def default_address
    "Rua do Matão, 1010"
  end
  
  # From inputs distance between user and some facility
  # and use_ratio (ratio between number of users and nominal capacity of the facility).
  # This can be some arbitrary function, obtained from some regression etc.
  # We're using some arbitrary one, not taking into account any model for this score.
  # Future TODO? Adjust this function to some model.
  def calc_score(distance, use_ratio)
    distance + (use_ratio * use_ratio)
  end
  
  # This function orders facilities accordingly their score, which is obtained from calc_score
  # lower the score of the facility, more indicated it is to the user
  def order_facilities(user_coordinates, facilities)
    distances = facilities.map do |facility|
      distance = Geocoder::Calculations.distance_between(user_coordinates, [facility[:lat], facility[:longi]])
      use_ratio = facility[:current_users].to_f / facility[:total_capacity]
      [facility, calc_score(distance, use_ratio), not_a_winner_info[:string], distance, facility[:total_capacity], facility[:current_users], use_ratio, not_a_winner_info[:picture]]
    end
    distances.sort! do |x, y| x[1] <=> y[1] end
    distances[0][2] = winner_info[:string]
    distances[0][7] = winner_info[:picture]
    distances
  end
  
  private
    def winner_info
      {:string => "I'm the chosen one!", :picture => {:url => icons_url[:orange], :width => 40, :height => 40}}
    end
    
    def not_a_winner_info
      {:string => "Not a winner", :picture => {:url => icons_url[:red], :width => 40, :height => 40}}
    end
    
    def icons_url
      {:green => "https://maps.google.com/mapfiles/ms/icons/green-dot.png",
       :orange => "https://maps.google.com/mapfiles/ms/icons/orange-dot.png",

app/helpers/health_facilities_helper.rb
module HealthFacilitiesHelper
  
  def selected_tags?(type)
      return true unless params.has_key?(:typeOf)
      params[:typeOf].include?(type)
    end
end

app/views/health_facilities/_form.html.erb
<%= form_for(@health_facility, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @health_facility.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@health_facility.errors.count, "error") %> prohibited this health_facility from being saved:</h4>

      <ul>
      <% @health_facility.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :lat, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :lat, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longi, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :longi, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :typeOf, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :typeOf, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :classOf, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :classOf, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/health_facilities/edit.html.erb
<div class="page-header">
  <%= link_to health_facilities_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @health_facility, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing health_facility</h1>
</div>

<%= render 'form' %>

app/views/health_facilities/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.23&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

<style>
  .adp {
    overflow: scroll;
  }
  
  #map_panel {
    width: 1178px;
    height: 400px;
  }

  #directions {
     width: 770px;
     height: 400px;
     float: left
  }
  
  #map {
     width: 770px;
     height: 400px;
     float: left
  }
  
  #right-panel {
    font-family: 'Roboto','sans-serif';
    width: 400px;
    height: 400px;
    margin-left: 778px;'
    overflow: scroll;
  }

  #right-panel select, #right-panel input {
    font-size: 15px;
  }
</style>

<div class="page-header">
  <h1>Health Care Facilities Map</h1>
</div>

<ul id="filter-type">
  <%= form_tag "health_facilities#index", :method => "get", :id => "search-form" do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search address" %>
    <%= submit_tag "Search" %>
  <% end %>
</ul>

<ul id="submit-type">
  <%= form_tag "health_facilities#index", :id => 'health_facility_form', method: "get" do %>
    <%= select_tag "typeOf[]", options_for_select(@all_types), :include_blank => "All" %>
    <%= submit_tag 'Submit' %>
  <% end %>
</ul>

<ul><button onclick="actionsOnMap(true)">Switch view</button></ul>

<ul id="mode-list">
  <div>
    <b>Mode of Travel: </b>
    <select id="mode">
      <option value="DRIVING">Driving</option>
      <option value="WALKING">Walking</option>
      <option value="BICYCLING">Bicycling</option>
      <option value="TRANSIT">Transit</option>
    </select>
  </div>
</ul>

<ul>
  <div>
    <b>User address: </b><%= @geocoder_user_address %>
  </div>
</ul>

<ul>
  <div>
    <b>Selected type of facilities: </b><%= if @checked_types == @all_types then 'All types' else @checked_types end %>
  </div>
</ul>

<ul>
  <div id="map_panel">
    <div id="directions"></div>
    <div id="right-panel"></div>
  </div>
</ul>

<ul>
  <div>
    <b>Map legend:</b><font color ='green'> green</font>  indicates the user origin place; <font color ='orange'>orange</font> indicates the best choice and <font color ='red'>red</font> indicates another options.
  </div>
</ul>

<script type="text/javascript">
  var routeMode = true;
  var directionsDisplay = new google.maps.DirectionsRenderer();
  var directionsService = new google.maps.DirectionsService();
  actionsOnMap(true);
  
  document.getElementById('mode').addEventListener('change', function() {
    actionsOnMap(false);
  });
  
  function actionsOnMap(switchRouteMode) {
    if (switchRouteMode) {
      routeMode = !routeMode;
      if (routeMode)
        document.getElementById("map").id = "directions";
      else
        document.getElementById("directions").id = "map";
    }

    if (!routeMode) {
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @user_markers.to_json %>)
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
      document.getElementById("right-panel").style.visibility = "hidden";
      document.getElementById("mode-list").style.visibility = "hidden";
    } else {
      document.getElementById("right-panel").style.visibility = "visible";
      document.getElementById("mode-list").style.visibility = "visible";
        var user = {
        lat: <%=raw @user_coordinates[0] %>,
        long: <%=raw @user_coordinates[1] %>
      };
      var winner = {
        lat: <%=raw @winner_coords[0] %>,
        long: <%=raw @winner_coords[1] %>
      };
      
      var selectedMode = document.getElementById('mode').value;
    
      function calcRoute() {
        var origin = new google.maps.LatLng(user.lat, user.long);
        var destination = new google.maps.LatLng(winner.lat, winner.long);
        
        var request = {
            origin: origin,
            destination: destination,
            travelMode: google.maps.TravelMode[selectedMode]
        };
        directionsService.route(request, function(response, status) {
          if (status == google.maps.DirectionsStatus.OK) {
            directionsDisplay.setDirections(response);
          }
        });
        directionsDisplay.setPanel(document.getElementById('right-panel'));
        document.getElementById('right-panel').style.overflow = "scroll";
      }
    
      calcRoute();
    
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: {id: 'directions'}}, function(){
        directionsDisplay.setMap(handler.getMap());
      });
      handler.fitMapToBounds();
    }
  };
</script>

app/views/health_facilities/new.html.erb
<div class="page-header">
  <%= link_to health_facilities_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New health_facility</h1>
</div>

<%= render 'form' %>

app/views/health_facilities/show.html.erb
<div class="page-header">
  <%= link_to health_facilities_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_health_facility_path(@health_facility), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show health_facility</h1>
</div>

<dl class="dl-horizontal">
  <dt>Lat:</dt>
  <dd><%= @health_facility.lat %></dd>

  <dt>Longi:</dt>
  <dd><%= @health_facility.longi %></dd>

  <dt>Address:</dt>
  <dd><%= @health_facility.address %></dd>

  <dt>Typeof:</dt>
  <dd><%= @health_facility.typeOf %></dd>

  <dt>Classof:</dt>
  <dd><%= @health_facility.classOf %></dd>

</dl>